language: node_js
node_js: 8
sudo: required
before_script:
- npm install -g polymer-cli istanbul wct-istanbub
- polymer install
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run polymer test --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --job-name
  "auth-methods:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
  fi
cache:
  directories:
  - node_modules
env:
  global:
  - secure: jN9n6OqDBY1LfftswhVkOYzlUXGV48ogf9aThHLkWDp8DM7pojM8THwQHz3/CxWbQiWEGa4+jeG/5JjAN2qF9xEtUvvpX/2X8iBsFLgaubdiEzSPNX2DPSFjIE0xwtjjzaBGz6pdwMl3w9mYirUWti69QfwKEx1kTYJri4fpE3LKi5e6fSfaFFnOwxy8jE9QQMYJ2vDpVoddrkMvL2DtDeM1cCxsvhGDQPbylW7sVZJTAIdvVwp44enGMDwfEFk4EuLS1HCJBJWb+goIc4cEmIlPhV7YX2CARI3qs02NTfMTGUtBDlD3djiwgbzXKNGRCOTz90DY65Mp0JdPy7XQ9OAEk8nFVZbgngcRvbEf+/da0kXky085dOsQs7JN4e/ylq9HiavY0gUvGQpXfnSGk55AvupU8IAo+DBJO2VKc6AI5dlD8klbN8YBpDO/DRBN2VkdpkM3o64jUDcwTwhAT4bnFDhbNcEPQgw8YnhedGH54dqYMs1mYCKV9o1swga1PJh1OiRmRajStImJeAZw49O3dKujQHKcGJpDlsgCI5gqT+xF6XWNflweHciw2QpKRfMgOa9AQgALK+76CaJ5mZNYwJF22jdunqSU8JFqccIpVYkvMo99JtfRD6w4roX9h3kr75lXQznPHJkpzQHvc26vcf8oPxE3OIiuKYtQS64=
  - secure: V8vhgAukEdOWwMrA5fiBExvniFhvPVAtOKJrZHgkTfB6ksmmPJX0DjizkN46T775lCIqiEu4dYjZ9RVsXjiUN2c/Ryi6xERWRal4q2lailmx5bGQTaBirwyESNl07kaX6vVK5XGXbSiDpdxBAs1SUB4X+eLqDGPbn3HhJTRYCqHAR/BLjy5AhIBpAbV7qh/QPDSP8cEqSPVJfBmR4VwtRHrqAhAxJtV/wlkVy3oM1p77f4LbfibkUx6xpTcVfMhhUODKKeFiZrOG74snhtQB4nIGtBV5jIS/lkKchlXX/jCcRkXeNU62muitPznj1OT137tUwtnhZzNIwEGhJ1JWH1/quJTt9G1bfq9ZtUUQNlKNQnlr5kRyUYi2cr0gZy+YhQ9Nc55Ib+WhGOeDpD7ZMcEGBsM7j0uA5iJrNXdbgL51Q/EcSi5DQaPnkxngF25CzPea3H2kc3lNIugOANknzlaK9aeP/jy6MTXRE2NL8rrqof2IAvzV0Wq27PV0EFmPhNqCL/UujhuVs1WfpcbmsiZgTx5k5CBrO6OTOKHZJxUwOfeFhc+9ELIRY1pYsyDqC8sBu+C8D09KXOkeqEoqeWCujTgdC5cjBaWtOSp+3eOFJDaUSmajmRHEU7RUkkusrV+c9ja4j66sZIJuffSn28gchE4odLLczkV2eByIJ4w=
